# JSFinder Configuration File
# Regex patterns for detecting secrets, API keys, and sensitive information

patterns:
  # AWS Credentials
  aws_access_key:
    pattern: '(?i)(aws_access_key_id|aws_access_key|aws_key_id)[\s]*[:=][\s]*["'']?([A-Z0-9]{20})["'']?'
    description: "AWS Access Key ID"
    confidence: "HIGH"
    
  aws_secret_key:
    pattern: '(?i)(aws_secret_access_key|aws_secret_key)[\s]*[:=][\s]*["'']?([A-Za-z0-9/+=]{40})["'']?'
    description: "AWS Secret Access Key"
    confidence: "HIGH"
    
  aws_session_token:
    pattern: '(?i)(aws_session_token)[\s]*[:=][\s]*["'']?([A-Za-z0-9/+=]{16,})["'']?'
    description: "AWS Session Token"
    confidence: "HIGH"

  # Google Cloud Platform
  gcp_api_key:
    pattern: '(?i)(gcp_api_key|google_api_key)[\s]*[:=][\s]*["'']?([A-Za-z0-9_-]{39})["'']?'
    description: "Google Cloud Platform API Key"
    confidence: "HIGH"
    
  gcp_service_key:
    pattern: '(?i)"type"[\s]*:[\s]*"service_account"'
    description: "Google Cloud Service Account Key"
    confidence: "HIGH"

  # Firebase
  firebase_api_key:
    pattern: '(?i)(firebase_api_key|firebase_key)[\s]*[:=][\s]*["'']?([A-Za-z0-9_-]{39})["'']?'
    description: "Firebase API Key"
    confidence: "HIGH"

  # GitHub
  github_token:
    pattern: '(?i)(github_token|gh_token)[\s]*[:=][\s]*["'']?(ghp_[A-Za-z0-9]{36}|gho_[A-Za-z0-9]{36}|ghu_[A-Za-z0-9]{36}|ghs_[A-Za-z0-9]{36}|ghr_[A-Za-z0-9]{36})["'']?'
    description: "GitHub Personal Access Token"
    confidence: "HIGH"

  # JWT Tokens
  jwt_token:
    pattern: '(?i)(jwt|token)[\s]*[:=][\s]*["'']?(eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*)["'']?'
    description: "JSON Web Token"
    confidence: "HIGH"

  # OAuth Tokens
  oauth_token:
    pattern: '(?i)(oauth_token|access_token|bearer_token)[\s]*[:=][\s]*["'']?([A-Za-z0-9_-]{20,})["'']?'
    description: "OAuth Access Token"
    confidence: "MEDIUM"

  # Generic API Keys
  api_key:
    pattern: '(?i)(api_key|apikey|api-key)[\s]*[:=][\s]*["'']?([A-Za-z0-9_-]{16,})["'']?'
    description: "Generic API Key"
    confidence: "MEDIUM"

  # Database URLs
  database_url:
    pattern: '(?i)(database_url|db_url)[\s]*[:=][\s]*["'']?(mongodb://|mysql://|postgres://|redis://)[^"''\s]+["'']?'
    description: "Database Connection URL"
    confidence: "MEDIUM"

  # Passwords
  password:
    pattern: '(?i)(password|passwd|pwd)[\s]*[:=][\s]*["'']?([^"''\s]{8,})["'']?'
    description: "Password or Credential"
    confidence: "MEDIUM"

  # Secrets
  secret:
    pattern: '(?i)(secret|secret_key)[\s]*[:=][\s]*["'']?([A-Za-z0-9_-]{16,})["'']?'
    description: "Secret Key"
    confidence: "MEDIUM"

  # Slack Tokens
  slack_token:
    pattern: '(?i)(slack_token|slack_api_token)[\s]*[:=][\s]*["'']?(xox[bpoa]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})["'']?'
    description: "Slack API Token"
    confidence: "HIGH"

  # Stripe Keys
  stripe_key:
    pattern: '(?i)(stripe_key|stripe_api_key)[\s]*[:=][\s]*["'']?(sk_live_[A-Za-z0-9]{24}|pk_live_[A-Za-z0-9]{24})["'']?'
    description: "Stripe API Key"
    confidence: "HIGH"

  # Twilio
  twilio_sid:
    pattern: '(?i)(twilio_sid|account_sid)[\s]*[:=][\s]*["'']?(AC[a-z0-9]{32})["'']?'
    description: "Twilio Account SID"
    confidence: "HIGH"

  # API Endpoints
  api_endpoint:
    pattern: '(?i)["'"](https?://[^"''\s]*/(api|admin|v[0-9]+)/[^"''\s]*)["'']'
    description: "API Endpoint URL"
    confidence: "LOW"

  # Internal Endpoints
  internal_endpoint:
    pattern: '(?i)["'"](/api/|/admin/|/internal/|/private/)[^"''\s]*["'']'
    description: "Internal/Private Endpoint"
    confidence: "LOW"

# Crawler settings
crawler:
  max_depth: 3
  threads: 10
  timeout: 30
  user_agent: "jsfinder/1.0"
  ignore_robots: false
  
# Scanner settings
scanner:
  threads: 10
  timeout: 30
  output_format: "json"
  
# Discovery settings
discovery:
  threads: 20
  timeout: 10
  max_redirects: 3
  status_filter: "200,201,202,204,301,302,307,308,401,403"
  user_agent: "jsfinder/1.0"

# Wordlists
wordlists:
  common_endpoints:
    - "api"
    - "admin"
    - "login"
    - "auth"
    - "users"
    - "user"
    - "config"
    - "settings"
    - "dashboard"
    - "profile"
    - "account"
    - "accounts"
    - "data"
    - "info"
    - "status"
    - "health"
    - "version"
    - "v1"
    - "v2"
    - "v3"
    - "test"
    - "debug"
    - "dev"
    - "staging"
    - "prod"
    - "production"